[package]
name = "console-ide"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
crossterm = "0.29.0"
instance-pipe = { git = "https://github.com/The-Infinitys/rust.instance-pipe" }
ipak = { git = "https://github.com/The-Infinitys/ipak" }
ratatui = { version = "0.29.0", features = ["all-widgets"] }
serde = { version = "1.0.225", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "2.0.16"
tui-term = "0.2.0"

# コア機能
console-ide-feature.path = "console-ide-feature"
